### PR TITLE
add svg support

### PR DESCRIPTION
**Pull request by mathias-h**

### CODE REVIEW

**Comment by mjbvz** [comment]
Closing as out-of scope as covered in #6

**Comment by malbernaz** [comment]
Why is this out of scope? Lit-html supports svg template tags : /

**Comment by mjbvz** [comment]
Ok, yes they do. Reopening.

If anyone wants to look into the implementation again, please create a separate scope for `svg` strings. We'll need to mark the bodies of these as being of language `svg` instead of language `html`

**Comment by malbernaz** [comment]
Thanks a lot mate. Will take a look on it later

**Comment by mjbvz** [comment]
Fixed by #26

**Pull request closed without merging**
