### PR TITLE
Fix Open quote highlighting

### PR DESCRIPTION
**Pull request by kufii**
some color themes use different colors for the quote than the contents, and the open quote wasn't being highlighted properly. See Screenshot:

issue

Notice how it's green instead of blue? This PR fixes this

### CODE REVIEW

**Comment by kufii** [comment]
tbh I think travis is wrong for the same reason by failing this, can someone correct me if I'm wrong? I don't think the CI should fail this

**Comment by mjbvz** [comment]
Change looks reasonable.

This repo has some baseline tests for the lit-html grammar. It looks like this change caused travis to fail. Try running `npm test` locally. It should probably change one of the grammar baseline file. Please include that changed file in the PR too.

**Comment by kufii** [comment]
worked for OS X, failed for linux for some reason. Any ideas?

**Comment by kufii** [comment]
@mjbvz just pinging you incase you didn't see, no rush though

**Comment by mjbvz** [comment]
Thanks! Merging since the failure seems unrelated. Will fix that

**Pull request merged**
